coreBookStore/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreBookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace coreBookStore.Controllers
{
    public class AuthorController : Controller
    {
        BookStoreDbContext context = new BookStoreDbContext();
        public ViewResult Index()
        {
            var auth = context.Authors.ToList();
            return View(auth);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Author a1)
        {

            context.Authors.Add(a1);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Author Authr = context.Authors.Where(x => x.AuthorId == id).SingleOrDefault();
            context.SaveChanges();
            return View(Authr);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Author auth = context.Authors.Find(id);
            return View(auth);
        }
        [HttpPost]
        public ActionResult Delete(int id, Author d1)
        {
            var auth = context.Authors.Where(x => x.AuthorId == id).SingleOrDefault();
            context.Authors.Remove(auth);
            context.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Author Authr = context.Authors.Where(x => x.AuthorId == id).SingleOrDefault();


            return View(Authr);
        }
        [HttpPost]
        public ActionResult Edit(Author a1)
        {
            Author Authr = context.Authors.Where
                (x => x.AuthorId == a1.AuthorId).SingleOrDefault();
            context.Entry(Authr).CurrentValues.SetValues(a1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

coreBookStore/Controllers/BookCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreBookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace coreBookStore.Controllers
{
    public class BookCategoryController : Controller
    {
        BookStoreDbContext context = new BookStoreDbContext();
        public ViewResult Index()
        {
            var caty = context.BookCategories.ToList();
            return View(caty);
        }
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(BookCategory c1)
        {
            context.BookCategories.Add(c1);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            BookCategory caty = context.BookCategories.Find(id);

            return View(caty);
        }
        [HttpPost]
        public ActionResult Delete(int id, BookCategory c1)
        {
            var caty = context.BookCategories.Where(x => x.BookCategoryId == id).SingleOrDefault();
            context.BookCategories.Remove(caty);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            BookCategory caty = context.BookCategories.Where(x => x.BookCategoryId == id).SingleOrDefault();


            return View(caty);
        }
        [HttpPost]
        public ActionResult Edit(BookCategory c1)
        {
            BookCategory caty = context.BookCategories.Where(x => x.BookCategoryId == c1.BookCategoryId).SingleOrDefault();
            context.Entry(caty).CurrentValues.SetValues(c1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            BookCategory caty = context.BookCategories.Where(x => x.BookCategoryId == id).SingleOrDefault();
            context.SaveChanges();
            return View(caty);
        }
    }
}

coreBookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreBookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace coreBookStore.Controllers
{
    public class BookController : Controller
    {
        BookStoreDbContext context = new BookStoreDbContext();
        public ViewResult Index()
        {
            var books = context.Books.ToList();
            return View(books);
        }
        [HttpGet]
        public ViewResult Create()
        {
            
            ViewBag.authors = new SelectList(context.Authors, "AuthorId", "AuthorName");
            ViewBag.categorys = new SelectList(context.BookCategories, "BookCategoryId", "BookCategoryName");
            ViewBag.publications = new SelectList(context.Publications, "PublicationId", "PublicationName");
           
            return View();
        }
        [HttpPost]
        public ActionResult Create(Book b1)
        {
            context.Books.Add(b1);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Book bk = context.Books.Find(id);

            return View(bk);
        }
        [HttpPost]
        public ActionResult Delete(int id, Book b1)
        {
            var bk = context.Books.Where(x => x.BookId == id).SingleOrDefault();
            context.Books.Remove(bk);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Book bk = context.Books.Where(x => x.BookId == id).SingleOrDefault();
            ViewBag.authors = new SelectList(context.Authors, "AuthorId", "AuthorName");
            ViewBag.categorys = new SelectList(context.BookCategories, "BookCategoryId", "BookCategoryName");
            ViewBag.publications = new SelectList(context.Publications, "PublicationId", "PublicationName");


            return View(bk);
        }
        [HttpPost]
        public ActionResult Edit(Book b1)
        {
            Book bk = context.Books.Where
                (x => x.BookId == b1.BookId).SingleOrDefault();
            context.Entry(bk).CurrentValues.SetValues(b1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            Book bk = context.Books.Where(x => x.BookId == id).SingleOrDefault();
            context.SaveChanges();
            return View(bk);
        }
    }
}

coreBookStore/Controllers/PublicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using coreBookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace coreBookStore.Controllers
{
    public class PublicationController : Controller
    {
        BookStoreDbContext context = new BookStoreDbContext();
        public ViewResult Index()
        {
            var publications = context.Publications.ToList();
            return View(publications);
        }
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Publication p1)
        {
            context.Publications.Add(p1);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Publication Pub = context.Publications.Where(x => x.PublicationId == id).SingleOrDefault();
            context.SaveChanges();
            return View(Pub);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Publication Pub = context.Publications.Find(id);

            return View(Pub);
        }
        [HttpPost]
        public ActionResult Delete(int id, Author p1)
        {
            var Pub = context.Publications.Where(x => x.PublicationId == id).SingleOrDefault();
            context.Publications.Remove(Pub);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Publication Pub = context.Publications.Where(x => x.PublicationId == id).SingleOrDefault();


            return View(Pub);
        }
        [HttpPost]
        public ActionResult Edit(Publication p1)
        {
            Publication Pub = context.Publications.Where
                (x => x.PublicationId == p1.PublicationId).SingleOrDefault();
            context.Entry(Pub).CurrentValues.SetValues(p1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

coreBookStore/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Http;
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OnlineBookStore- Admin Portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Starter.css" />
    <link rel="stylesheet" href="~/css/Home.css" />
         

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Online Book Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Author" asp-action="Index">Author</a>
                </li>
               
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Publication" asp-action="Index">Publication</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="BookCategory" asp-action="Index">Category</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Book" asp-action="Index">Books</a>
                </li>
                @*<li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>*@
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <label class="form-control">
                    Welcome @Context.Session.GetString("uname")!!
                </label>
                &nbsp;
                <a asp-action="Logout" asp-controller="Account" class="btn btn-success">Logout</a>
            </form>
        </div>
    </nav>
    <main role="main" class="container">

        @RenderBody()
        <hr>
    </main><!-- /.container -->

    <footer class="container">
        <p>&copy; Online Book Store - 2019</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>
</html>

coreBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - coreBookStore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">coreBookStore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - coreBookStore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>